FROM golang:1.22 AS builder

WORKDIR /app
COPY backend/ /app/
RUN go mod tidy
RUN CGO_ENABLED=0 go build -o app .

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/app .

# Add CA certificates and timezone data
RUN apk add --no-cache ca-certificates tzdata

EXPOSE 8081
CMD ["./app"]