name: CI

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main
      
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: '1.24'
          cache: false
      - name: Install deps
        run: go mod download
        working-directory: backend   
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          args: --timeout=15m
